# Window
WINDOW_TITLE = "Stock App"
WINDOW_INIT_WIDTH = 1024
WINDOW_INIT_HEIGHT = 768
WINDOW_MIN_WIDTH = 800
WINDOW_MIN_HEIGHT = 600

# Layout
MARGIN_ROOT = 12
SPACING_ROOT = 8


# Landing page
SPACING_LANDING = 20


# Portfolio Analysis
SIDEBAR_PA_WIDTH = 220
SIDEBAR_PA_LIST_HEIGHT = 150

SPACING_PA_ROOT = 0
SPACING_PA_SIDEBAR = 12
SPACING_PA_DIVIDER = 8
SPACING_PA_SELECTED = 4

MARGIN_PA_ROOT = 0
MARGIN_PA_SIDEBAR = 12

DROPDOWN_PA_HEIGHT = 120
DROPDOWN_MAX_ITEMS = 8

LABEL_PA_BACK = "← Back"
LABEL_PA_EXCHANGE = "Exchanges"
LABEL_PA_COUNTRIES = "Countries"
LABEL_PA_SECTOR = "Sectors"
LABEL_PA_SELECTED = "Selected:"
LABEL_PA_SELECT_EXCHANGE = "-- Select Exchange --"
LABEL_PA_SELECT_COUNTRY = "-- Select Country --"
LABEL_PA_SELECT_SECTOR = "-- Select Sector --"
LABEL_PA_SELECT_EXCHANGE_TO_BEGIN = "Select exchanges to begin analysis"


# Ticket Selector
MARGIN_TICKER_SIDEBAR = 12
SPACING_TICKER_SIDEBAR = 8
WIDTH_TICKER_LIST = 300
