# Window
WINDOW_TITLE = "Stock App"
WINDOW_INIT_WIDTH = 1024
WINDOW_INIT_HEIGHT = 768
WINDOW_MIN_WIDTH = 800
WINDOW_MIN_HEIGHT = 600

# Layout
MARGIN_ROOT = 12
SPACING_ROOT = 8


# Landing page
SPACING_LANDING = 20


# Portfolio Analysis
SIDEBAR_PA_WIDTH = 220

SPACING_PA_ROOT = 0
SPACING_PA_SIDEBAR = 12
SPACING_PA_DIVIDER = 8
SPACING_PA_SELECTED = 4

MARGIN_PA_ROOT = 0
MARGIN_PA_SIDEBAR = 12

LABEL_PA_BACK = "← Back"
LABEL_PA_EXCHANGE = "Exchanges"
LABEL_PA_SELECTED = "Selected:"
LABEL_PA_SELECT_EXCHANGE = "Select exchanges to begin analysis"
